# Generated by Django 2.0 on 2018-09-11 09:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('dam_asset', models.URLField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_external_id', models.CharField(max_length=64, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Update date')),
            ],
        ),
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_configuration', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('state', models.CharField(choices=[('empty', 'Empty')], default='empty', max_length=64)),
                ('activity_log', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elsepdm.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='ProductComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('configurable', models.BooleanField()),
                ('visible', models.BooleanField()),
                ('optional', models.BooleanField()),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('configurable', models.BooleanField()),
                ('path', models.CharField(max_length=64)),
                ('active_material', models.CharField(max_length=64)),
                ('active_color', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ProductHierarchy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='elsepdm.Product')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elsepdm.ProductComponent')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.CharField(max_length=64)),
                ('resolution_x', models.PositiveIntegerField()),
                ('resolution_y', models.PositiveIntegerField()),
                ('frames', models.PositiveIntegerField()),
                ('circles', models.PositiveIntegerField()),
                ('frame_rate', models.PositiveIntegerField()),
                ('filename', models.CharField(max_length=64)),
                ('extended_json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elsepdm.ProductRevision')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dam_asset', models.URLField(max_length=10000)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='elsepdm.ProductRevision')),
            ],
        ),
        migrations.AddField(
            model_name='productelement',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elsepdm.ProductStructure'),
        ),
        migrations.AddField(
            model_name='productcomponent',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elsepdm.ProductRevision'),
        ),
        migrations.AddField(
            model_name='product',
            name='previous_revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='elsepdm.ProductRevision'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_hierarchy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elsepdm.ProductHierarchy'),
        ),
        migrations.AddField(
            model_name='product',
            name='revision_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='elsepdm.ProductRevision'),
        ),
        migrations.AddField(
            model_name='manifest',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='elsepdm.ProductRevision'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elsepdm.AssetType'),
        ),
        migrations.AddField(
            model_name='asset',
            name='product_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elsepdm.ProductStructure'),
        ),
    ]
