# Generated by Django 2.0 on 2018-09-14 13:38

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('elsepdm', '0002_auto_20180914_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='dam_asset',
        ),
        migrations.AddField(
            model_name='asset',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='resource_type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='temporary',
            field=models.BooleanField(default=False, verbose_name='Temporary'),
        ),
        migrations.AddField(
            model_name='asset',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
