# Generated by Django 2.0 on 2018-09-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsepdm', '0005_auto_20180914_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damasset',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='damasset',
            name='name',
        ),
        migrations.RemoveField(
            model_name='damasset',
            name='resource_type',
        ),
        migrations.RemoveField(
            model_name='damasset',
            name='temporary',
        ),
        migrations.RemoveField(
            model_name='damasset',
            name='uuid',
        ),
        migrations.AddField(
            model_name='productrevision',
            name='state',
            field=models.CharField(choices=[('manifest', 'Manifest'), ('published', 'Published')], default='manifest', max_length=64),
        ),
    ]
