# Generated by Django 2.0 on 2018-09-24 13:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elsepdm', '0007_auto_20180924_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifest',
            name='product',
        ),
        migrations.AddField(
            model_name='productrevision',
            name='json_configuration',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='Manifest',
        ),
    ]
