# Generated by Django 2.0 on 2018-09-25 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elsepdm', '0008_auto_20180924_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomponent',
            name='component',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productelement',
            name='element',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productstructure',
            name='structure',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcomponent',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_components', to='elsepdm.ProductRevision'),
        ),
        migrations.AlterField(
            model_name='productelement',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_elements', to='elsepdm.ProductStructure'),
        ),
        migrations.AlterField(
            model_name='productstructure',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_structures', to='elsepdm.ProductComponent'),
        ),
    ]
