# Generated by Django 2.0 on 2018-09-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsepdm', '0011_auto_20180927_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrevision',
            name='product_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
