# Generated by Django 2.0 on 2018-09-28 10:37

from django.db import migrations, models
import elsepdm.models


class Migration(migrations.Migration):

    dependencies = [
        ('elsepdm', '0012_productrevision_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='file',
            field=models.FileField(null=True, upload_to=elsepdm.models.generate_file_name),
        ),
    ]
