# Generated by Django 2.0 on 2018-09-28 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elsepdm', '0013_asset_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='dam_asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elsepdm.DamAsset'),
        ),
    ]
