# Generated by Django 2.0 on 2018-09-28 14:01

from django.db import migrations, models
import elsepdm.models


class Migration(migrations.Migration):

    dependencies = [
        ('elsepdm', '0015_productstructure_export_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(max_length=400, null=True, upload_to=elsepdm.models.generate_file_name),
        ),
    ]
