# Generated by Django 2.0 on 2018-11-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsepdm', '0017_productrevision_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damasset',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='damasset',
            name='name',
        ),
        migrations.RemoveField(
            model_name='damasset',
            name='uuid',
        ),
        migrations.AddField(
            model_name='damasset',
            name='brand_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='damasset',
            name='dam_uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='damasset',
            name='description',
            field=models.TextField(blank=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='damasset',
            name='extension',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='damasset',
            name='filename',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='damasset',
            name='meta_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='damasset',
            name='mime_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='damasset',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='damasset',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='damasset',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='damasset',
            name='resource_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
