# Generated by Django 2.0 on 2018-12-07 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elsepdm', '0018_auto_20181119_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damasset',
            name='description',
        ),
        migrations.RemoveField(
            model_name='damasset',
            name='mime_type',
        ),
        migrations.RemoveField(
            model_name='damasset',
            name='temporary',
        ),
    ]
