# Generated by Django 2.0 on 2018-12-11 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elsepdm', '0019_auto_20181207_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset_type',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='dam_asset',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='product_structure',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='previous_revision',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_hierarchy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='revision_number',
        ),
        migrations.RemoveField(
            model_name='productcomponent',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productelement',
            name='structure',
        ),
        migrations.RemoveField(
            model_name='productrevision',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productstructure',
            name='component',
        ),
        migrations.RemoveField(
            model_name='producttour',
            name='product',
        ),
        migrations.RemoveField(
            model_name='templateproduct',
            name='dam_asset',
        ),
        migrations.RemoveField(
            model_name='templateproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='AssetType',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='DamAsset',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductComponent',
        ),
        migrations.DeleteModel(
            name='ProductElement',
        ),
        migrations.DeleteModel(
            name='ProductHierarchy',
        ),
        migrations.DeleteModel(
            name='ProductRevision',
        ),
        migrations.DeleteModel(
            name='ProductStructure',
        ),
        migrations.DeleteModel(
            name='ProductTour',
        ),
        migrations.DeleteModel(
            name='TemplateProduct',
        ),
    ]
