# Generated by Django 2.0 on 2018-12-22 13:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elsepdm', '0020_auto_20181211_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update')),
                ('brand_external_id', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponentAsset',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update')),
                ('dam_uuid', models.UUIDField(null=True)),
                ('filename', models.CharField(max_length=255, null=True)),
                ('size', models.BigIntegerField(default=0)),
                ('extension', models.CharField(max_length=255, null=True)),
                ('brand_id', models.CharField(blank=True, max_length=64, null=True)),
                ('url', models.URLField(null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('resource_type', models.CharField(max_length=255, null=True)),
                ('meta_info', models.TextField(blank=True, null=True)),
                ('asset_type', models.CharField(choices=[('MODEL_ASSET', 'Model asset'), ('PREVIEW_ASSET', 'Preview asset'), ('B4W_ASSET', 'B4W asset'), ('TOUR_GIF_ASSET', 'Tour gif asset'), ('FRAMES_ASSET', 'Frames asset')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update')),
                ('state', models.CharField(choices=[('created', 'Created'), ('rendered', 'Rendered'), ('published', 'Published')], default='created', max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConfigurationElement',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update')),
                ('material', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=64)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_elements', to='elsepdm.Configuration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update')),
                ('state', models.CharField(choices=[('empty', 'Empty')], default='empty', max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('sku', models.CharField(max_length=64)),
                ('activity_log', models.TextField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elsepdm.Brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductAsset',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update')),
                ('dam_uuid', models.UUIDField(null=True)),
                ('filename', models.CharField(max_length=255, null=True)),
                ('size', models.BigIntegerField(default=0)),
                ('extension', models.CharField(max_length=255, null=True)),
                ('brand_id', models.CharField(blank=True, max_length=64, null=True)),
                ('url', models.URLField(null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('resource_type', models.CharField(max_length=255, null=True)),
                ('meta_info', models.TextField(blank=True, null=True)),
                ('asset_type', models.CharField(choices=[('MODEL_ASSET', 'Model asset'), ('PREVIEW_ASSET', 'Preview asset'), ('B4W_ASSET', 'B4W asset'), ('TOUR_GIF_ASSET', 'Tour gif asset'), ('FRAMES_ASSET', 'Frames asset')], max_length=255)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='elsepdm.Configuration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductComponent',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update')),
                ('name', models.CharField(max_length=64)),
                ('component', models.CharField(max_length=64)),
                ('configurable', models.BooleanField()),
                ('visible', models.BooleanField()),
                ('optional', models.BooleanField()),
                ('order', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductElement',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update')),
                ('name', models.CharField(max_length=64)),
                ('element', models.CharField(max_length=64)),
                ('configurable', models.BooleanField()),
                ('path', models.CharField(max_length=64)),
                ('active_material', models.CharField(max_length=64)),
                ('active_color', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductHierarchy',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductRevision',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update')),
                ('state', models.CharField(choices=[('new', 'New'), ('updated', 'Updated'), ('parsed', 'Parsed'), ('ready', 'Ready'), ('publishing', 'Publishing'), ('published', 'Published')], default='new', max_length=64)),
                ('json_configuration', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='elsepdm.Product')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ProductStructure',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update')),
                ('name', models.CharField(max_length=64)),
                ('export_name', models.CharField(max_length=255)),
                ('structure', models.CharField(max_length=64)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_structures', to='elsepdm.ProductComponent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductTour',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update')),
                ('name', models.CharField(max_length=255)),
                ('camera', models.CharField(max_length=64)),
                ('resolution_x', models.PositiveIntegerField()),
                ('resolution_y', models.PositiveIntegerField()),
                ('frames', models.PositiveIntegerField()),
                ('circles', models.PositiveIntegerField()),
                ('frame_rate', models.PositiveIntegerField()),
                ('filename', models.CharField(max_length=64)),
                ('extended_json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elsepdm.ProductRevision')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='productelement',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_elements', to='elsepdm.ProductStructure'),
        ),
        migrations.AddField(
            model_name='productcomponent',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_components', to='elsepdm.ProductRevision'),
        ),
        migrations.AddField(
            model_name='product',
            name='previous_revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='elsepdm.ProductRevision'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_hierarchy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elsepdm.ProductHierarchy'),
        ),
        migrations.AddField(
            model_name='product',
            name='revision_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='elsepdm.ProductRevision'),
        ),
        migrations.AddField(
            model_name='configurationelement',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elsepdm.ProductElement'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='product_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elsepdm.ProductRevision'),
        ),
        migrations.AddField(
            model_name='componentasset',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='elsepdm.ProductStructure'),
        ),
    ]
