# Generated by Django 2.0 on 2019-01-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsepdm', '0021_auto_20181222_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomponent',
            name='configurable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productcomponent',
            name='optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productcomponent',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productelement',
            name='configurable',
            field=models.BooleanField(default=True),
        ),
    ]
