# Generated by Django 2.0 on 2019-01-28 15:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsepdm', '0023_auto_20190128_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='productelement',
            name='materials',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=[], size=None),
        ),
    ]
