# Generated by Django 2.0 on 2019-02-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsepdm', '0024_productelement_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productelement',
            name='active_material',
            field=models.CharField(max_length=64),
        ),
    ]
