# Generated by Django 2.0 on 2019-03-14 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elsepdm', '0026_pdm_material_and_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elsepdm.Collection'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_hierarchy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elsepdm.ProductHierarchy'),
        ),
    ]
