# Generated by Django 2.0 on 2019-03-24 11:17

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elsepdm', '0027_make_collection_field_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='elsepdm.Brand'),
        ),
        migrations.AlterField(
            model_name='productelement',
            name='materials',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None),
        ),
    ]
