# Generated by Django 2.1.7 on 2019-04-11 09:38

import uuid

import django.db.models.deletion
from django.db import (
    models,
    migrations,
)
from django.contrib.postgres import fields


class Migration(migrations.Migration):

    dependencies = [
        ('elsepdm', '0029_auto_20190404_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoePairSettings', fields=[
                ('deleted', models.DateTimeField(
                    editable=False,
                    null=True,
                )),
                ('uuid', models.UUIDField(
                    default=uuid.uuid4,
                    editable=False,
                    primary_key=True,
                    serialize=False,
                    unique=True,
                )),
                ('created', models.DateTimeField(
                    auto_now_add=True,
                    null=True,
                    verbose_name='Date',
                )),
                ('updated', models.DateTimeField(
                    auto_now=True,
                    verbose_name='Update',
                )),
                ('name', models.CharField(
                    max_length=120,
                )),
                ('axes', models.CharField(
                    choices=[
                        ('xyz', 'XYZ'),
                        ('xzy', 'XZY'),
                        ('yxz', 'YXZ'),
                        ('yzx', 'YZX'),
                        ('zxy', 'ZXY'),
                        ('zyx', 'ZYX'),
                    ],
                    max_length=3,
                )),
                ('distance', models.FloatField(
                    verbose_name='Distance between models',
                )),
                ('shouldnt_be_reflected', fields.ArrayField(
                    base_field=models.CharField(max_length=200),
                    default=list,
                    size=None,
                    verbose_name='Objects that should not be reflected',
                )),
                ('brand', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='elsepdm.Brand',
                )),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
