# Generated by Django 2.1.7 on 2019-04-26 15:12

import uuid

import django.db.models.deletion
from django.db import (
    models,
    migrations,
)


class Migration(migrations.Migration):

    dependencies = [
        ('elsepdm', '0031_shoepairsettingsproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceAsset',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update')),
                ('dam_uuid', models.UUIDField(null=True)),
                ('filename', models.CharField(max_length=255, null=True)),
                ('size', models.BigIntegerField(default=0)),
                ('extension', models.CharField(max_length=255, null=True)),
                ('brand_id', models.CharField(blank=True, max_length=64, null=True)),
                ('url', models.URLField(null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('resource_type', models.CharField(max_length=255, null=True)),
                ('meta_info', models.TextField(blank=True, null=True)),
                ('asset_type', models.CharField(choices=[('MODEL_ASSET', 'Model asset'), ('PREVIEW_ASSET', 'Preview asset'), ('B4W_ASSET', 'B4W asset'), ('TOUR_GIF_ASSET', 'Tour gif asset'), ('FRAMES_ASSET', 'Frames asset'), ('OBJ_ASSET', 'Obj asset'), ('BLEND_RESOURCE', 'Resource asset')], max_length=255)),
                ('type', models.CharField(choices=[('ENV', 'Environment'), ('SETTINGS', 'Settings'), ('BACKGROUND', 'Background')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('pdm_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_assets', to='elsepdm.Brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='componentasset',
            name='asset_type',
            field=models.CharField(choices=[('MODEL_ASSET', 'Model asset'), ('PREVIEW_ASSET', 'Preview asset'), ('B4W_ASSET', 'B4W asset'), ('TOUR_GIF_ASSET', 'Tour gif asset'), ('FRAMES_ASSET', 'Frames asset'), ('OBJ_ASSET', 'Obj asset'), ('BLEND_RESOURCE', 'Resource asset')], max_length=255),
        ),
        migrations.AlterField(
            model_name='productasset',
            name='asset_type',
            field=models.CharField(choices=[('MODEL_ASSET', 'Model asset'), ('PREVIEW_ASSET', 'Preview asset'), ('B4W_ASSET', 'B4W asset'), ('TOUR_GIF_ASSET', 'Tour gif asset'), ('FRAMES_ASSET', 'Frames asset'), ('OBJ_ASSET', 'Obj asset'), ('BLEND_RESOURCE', 'Resource asset')], max_length=255),
        ),
    ]
