# Generated by Django 2.1.7 on 2019-04-30 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elsepdm', '0032_add_resource'),
        ('elsepdm', '0032_auto_20190426_1353'),
    ]

    operations = [
    ]
