# Generated by Django 2.1.7 on 2019-06-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsepdm', '0036_auto_20190516_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='state',
            field=models.CharField(choices=[(0, 'New'), (1, 'Updated'), (2, 'Preparing'), (3, 'Prepared'), (4, 'Publishing'), (5, 'Published')], default=0, max_length=64),
        ),
    ]
