# Generated by Django 2.1.7 on 2019-05-24 10:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('elsepdm', '0037_material_available_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update')),
                ('name', models.CharField(max_length=64)),
                ('color_space', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=225)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ColorGroup',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='material',
            name='available_colors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elsepdm.Color'),
        ),
        migrations.AddField(
            model_name='color',
            name='color_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='elsepdm.ColorGroup'),
        ),
    ]
