# Generated by Django 2.1.7 on 2019-05-31 11:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('elsepdm', '0038_auto_20190524_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialImplementation',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update')),
                ('name', models.CharField(max_length=255)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implementations', to='elsepdm.Color')),
            ],
        ),
        migrations.RemoveField(
            model_name='material',
            name='available_colors',
        ),
        migrations.AddField(
            model_name='materialimplementation',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implementations', to='elsepdm.Material'),
        ),
        migrations.AddField(
            model_name='material',
            name='available_colors',
            field=models.ManyToManyField(through='elsepdm.MaterialImplementation', to='elsepdm.Color'),
        ),
        migrations.AlterUniqueTogether(
            name='materialimplementation',
            unique_together={('name', 'material', 'deleted')},
        ),
    ]
