# Generated by Django 2.1.7 on 2019-06-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elsepdm', '0039_auto_20190531_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color_space',
            new_name='external_id',
        ),
        migrations.RemoveField(
            model_name='color',
            name='color_group',
        ),
        migrations.RemoveField(
            model_name='color',
            name='description',
        ),
        migrations.RemoveField(
            model_name='color',
            name='value',
        ),
        migrations.DeleteModel(
            name='ColorGroup',
        ),
    ]
