# Generated by Django 2.0 on 2018-08-29 15:12

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('brand_external_id', models.CharField(max_length=64, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Update date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DamAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('status', models.CharField(max_length=255)),
                ('resource_type', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, verbose_name='About')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('temporary', models.BooleanField(default=False, verbose_name='Temporary')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('filename', models.CharField(max_length=255)),
                ('extension', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=255)),
                ('size', models.BigIntegerField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='elsedam.DamAsset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('storage_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('buffered', 'Buffered')], max_length=255)),
                ('account_name', models.CharField(max_length=255)),
                ('account_key', models.CharField(max_length=255)),
                ('storage_timeout', models.IntegerField()),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StorageGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('file_extensions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('mime_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='elsedam.Storage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='buffered_storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buffered_storage', to='elsedam.Storage'),
        ),
        migrations.AddField(
            model_name='brand',
            name='private_storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_storage', to='elsedam.Storage'),
        ),
        migrations.AddField(
            model_name='brand',
            name='public_storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_storage', to='elsedam.Storage'),
        ),
    ]
