# Generated by Django 2.0 on 2018-08-30 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elsedam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='buffered_storage',
            field=models.ForeignKey(limit_choices_to={'storage_type': 'buffered'}, on_delete=django.db.models.deletion.CASCADE, related_name='buffered_storage', to='elsedam.Storage'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='private_storage',
            field=models.ForeignKey(limit_choices_to={'storage_type': 'private'}, on_delete=django.db.models.deletion.CASCADE, related_name='private_storage', to='elsedam.Storage'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='public_storage',
            field=models.ForeignKey(limit_choices_to={'storage_type': 'public'}, on_delete=django.db.models.deletion.CASCADE, related_name='public_storage', to='elsedam.Storage'),
        ),
    ]
