# Generated by Django 2.0 on 2018-08-31 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elsedam', '0002_auto_20180830_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='BufferedDamAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buffer_url', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('buffering', 'Buffering'), ('buffered', 'Buffered'), ('failed_to_buffer', 'FailedToBuffer')], max_length=64)),
                ('last_request', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CdnDamAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdn_url', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('failed_to_upload', 'FailedToUpload')], max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='DamAssetRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elsedam.BufferedDamAsset')),
            ],
        ),
        migrations.RemoveField(
            model_name='file',
            name='asset',
        ),
        migrations.AddField(
            model_name='brand',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='damasset',
            name='brand_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='damasset',
            name='extension',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='damasset',
            name='filename',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='damasset',
            name='mime_type',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='damasset',
            name='size',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='damasset',
            name='tags',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storagegroup',
            name='brand',
            field=models.ForeignKey(default='', limit_choices_to={'is_default': True}, on_delete=django.db.models.deletion.CASCADE, to='elsedam.Brand'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AddField(
            model_name='damasset',
            name='buffered_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elsedam.BufferedDamAsset'),
        ),
        migrations.AddField(
            model_name='damasset',
            name='cdn_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elsedam.CdnDamAsset'),
        ),
    ]
