# Generated by Django 2.0 on 2018-09-03 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elsedam', '0003_auto_20180831_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damasset',
            name='name',
        ),
        migrations.RemoveField(
            model_name='damasset',
            name='status',
        ),
        migrations.AddField(
            model_name='damasset',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='elsedam.StorageGroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='damasset',
            name='state',
            field=models.CharField(choices=[('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('failed_to_upload', 'FailedToUpload')], default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storage',
            name='container',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
