# Generated by Django 2.0 on 2018-09-04 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elsedam', '0004_auto_20180903_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='damasset',
            name='body',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='storage_timeout',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagegroup',
            name='brand',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_default': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='elsedam.Brand'),
        ),
    ]
