# Generated by Django 2.0 on 2018-09-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsedam', '0005_auto_20180904_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='damasset',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
