# Generated by Django 2.0 on 2018-09-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsedam', '0006_damasset_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='damasset',
            name='product_uuid',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
