# Generated by Django 2.0 on 2018-10-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsedam', '0008_auto_20181009_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='buffereddamasset',
            name='for_removing',
            field=models.BooleanField(default=False),
        ),
    ]
