# Generated by Django 2.0 on 2018-10-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsedam', '0009_buffereddamasset_for_removing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buffereddamasset',
            name='last_request',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='buffereddamasset',
            name='state',
            field=models.CharField(choices=[('buffering', 'Buffering'), ('buffered', 'Buffered'), ('failed_to_buffer', 'FailedToBuffer')], default='buffering', max_length=64),
        ),
    ]
