# Generated by Django 2.0 on 2018-10-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elsedam', '0011_auto_20181012_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='azurestorage',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='damasset',
            name='buffered_asset',
        ),
        migrations.RemoveField(
            model_name='damasset',
            name='cdn_asset',
        ),
        migrations.RemoveField(
            model_name='damasset',
            name='group',
        ),
        migrations.RemoveField(
            model_name='damassetrequest',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='storagegroup',
            name='brand',
        ),
    ]
