# Generated by Django 2.0 on 2018-10-12 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elsedam', '0012_auto_20181012_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='azurestorage',
            name='brand',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elsedam.Brand'),
        ),
        migrations.AddField(
            model_name='damasset',
            name='buffered_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elsedam.BufferedDamAsset'),
        ),
        migrations.AddField(
            model_name='damasset',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='elsedam.StorageGroup'),
        ),
        migrations.AddField(
            model_name='damassetrequest',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='elsedam.BufferedDamAsset'),
        ),
        migrations.AddField(
            model_name='storagegroup',
            name='brand',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_default': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='elsedam.Brand'),
        ),
    ]
