# Generated by Django 2.0 on 2018-10-15 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elsedam', '0013_auto_20181012_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azurestoragelocation',
            name='storage',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='elsedam.AzureStorage'),
        ),
    ]
