# Generated by Django 2.0 on 2018-10-15 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('elsedam', '0014_auto_20181015_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='buffereddamasset',
            name='location_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='buffereddamasset',
            name='location_uuid',
            field=models.UUIDField(null=True),
        ),
    ]
