# Generated by Django 2.0 on 2018-10-16 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elsedam', '0015_auto_20181015_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damassetrequest',
            name='asset',
        ),
        migrations.AddField(
            model_name='damassetrequest',
            name='buffered_asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='requests', to='elsedam.BufferedDamAsset'),
        ),
        migrations.AlterField(
            model_name='azurestorage',
            name='brand',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='elsedam.Brand'),
        ),
        migrations.AlterField(
            model_name='azurestoragelocation',
            name='storage',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='locations', to='elsedam.AzureStorage'),
        ),
        migrations.AlterField(
            model_name='buffereddamasset',
            name='location_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='damasset',
            name='buffered_asset',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='elsedam.BufferedDamAsset'),
        ),
        migrations.AlterField(
            model_name='damasset',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assets', to='elsedam.StorageGroup'),
        ),
        migrations.AlterField(
            model_name='damasset',
            name='location_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='storagegroup',
            name='location_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType'),
        ),
    ]
