# Generated by Django 2.0 on 2018-10-23 15:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsedam', '0016_auto_20181016_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damasset',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None),
        ),
    ]
