# Generated by Django 2.0 on 2018-10-24 11:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('elsedam', '0017_auto_20181023_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damasset',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='damasset',
            name='id',
        ),
        migrations.AlterField(
            model_name='damasset',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
