# Generated by Django 2.0 on 2018-10-30 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elsedam', '0018_auto_20181024_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='azurestorage',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='azurestoragelocation',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='azurestoragelocation',
            name='storagelocation_ptr',
        ),
        migrations.DeleteModel(
            name='AzureStorage',
        ),
        migrations.DeleteModel(
            name='AzureStorageLocation',
        ),
    ]
