# Generated by Django 2.0 on 2018-10-30 08:54

from django.db import migrations, models
import django.db.models.deletion
import elsedam.services
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('elsedam', '0019_auto_20181030_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzureStorageLocation',
            fields=[
                ('storagelocation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='elsedam.StorageLocation')),
                ('container', models.CharField(editable=False, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('elsedam.storagelocation',),
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update')),
                ('domain', models.CharField(max_length=255)),
                ('storage_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('buffered', 'Buffered')], editable=False, max_length=255)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, elsedam.services.StorageService),
        ),
        migrations.CreateModel(
            name='AzureStorage',
            fields=[
                ('storage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='elsedam.Storage')),
                ('account_name', models.CharField(editable=False, max_length=255)),
                ('account_key', models.CharField(editable=False, max_length=255)),
                ('container', models.CharField(editable=False, max_length=255)),
                ('storage_timeout', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('elsedam.storage', elsedam.services.AzureService),
        ),
        migrations.AddField(
            model_name='storage',
            name='brand',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='elsedam.Brand'),
        ),
        migrations.AddField(
            model_name='azurestoragelocation',
            name='storage',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='locations', to='elsedam.AzureStorage'),
        ),
    ]
