# Generated by Django 2.0 on 2018-11-02 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elsedam', '0020_auto_20181030_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='azurestoragelocation',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='buffereddamasset',
            name='location_type',
        ),
        migrations.RemoveField(
            model_name='buffereddamasset',
            name='location_uuid',
        ),
        migrations.RemoveField(
            model_name='damasset',
            name='body',
        ),
        migrations.RemoveField(
            model_name='damasset',
            name='buffered_asset',
        ),
        migrations.RemoveField(
            model_name='damasset',
            name='location_type',
        ),
        migrations.RemoveField(
            model_name='damasset',
            name='location_uuid',
        ),
        migrations.RemoveField(
            model_name='damasset',
            name='product_uuid',
        ),
        migrations.RemoveField(
            model_name='storagegroup',
            name='location_type',
        ),
        migrations.RemoveField(
            model_name='storagegroup',
            name='location_uuid',
        ),
        migrations.AddField(
            model_name='buffereddamasset',
            name='dam_asset',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='buffered_asset', to='elsedam.DamAsset'),
        ),
        migrations.AddField(
            model_name='buffereddamasset',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='buffered_assets', to='elsedam.StorageLocation'),
        ),
        migrations.AddField(
            model_name='buffereddamasset',
            name='meta_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='damasset',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assets', to='elsedam.StorageLocation'),
        ),
        migrations.AddField(
            model_name='damasset',
            name='meta_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='model_type',
            field=models.CharField(default='storage', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='storagegroup',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='storage_groups', to='elsedam.StorageLocation'),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='model_type',
            field=models.CharField(default='storagelocation', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='storage',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='locations', to='elsedam.Storage'),
        ),
        migrations.AlterField(
            model_name='buffereddamasset',
            name='state',
            field=models.CharField(choices=[('buffering', 'Buffering'), ('buffered', 'Buffered'), ('failed_to_buffer', 'FailedToBuffer'), ('failed_to_remove', 'FailedToRemove')], default='buffering', max_length=64),
        ),
        migrations.AlterField(
            model_name='damasset',
            name='state',
            field=models.CharField(choices=[('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('failed_to_upload', 'FailedToUpload'), ('failed_to_remove', 'FailedToRemove')], max_length=255),
        ),
    ]
