# Generated by Django 2.0 on 2018-11-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsedam', '0021_auto_20181102_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='buffereddamasset',
            name='buffer_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
