# Generated by Django 2.0 on 2018-11-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsedam', '0022_buffereddamasset_buffer_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damassetrequest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date'),
        ),
    ]
