# Generated by Django 2.0 on 2018-11-14 07:53

from django.db import migrations


def create_default_brand(apps, schema_editor):
    Brand = apps.get_model('elsedam', 'Brand')
    Brand.objects.create(is_default=True, brand_external_id='0')


class Migration(migrations.Migration):


    dependencies = [
        ('elsedam', '0023_auto_20181113_1259'),
    ]

    operations = [
        migrations.RunPython(create_default_brand),
    ]
