# Generated by Django 2.0 on 2019-03-06 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elsedam', '0026_damassetbatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damasset',
            name='resource_type',
        ),
        migrations.AddField(
            model_name='damasset',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='elsedam.DamAssetBatch'),
        ),
    ]
