# Generated by Django 2.0 on 2019-03-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsedam', '0027_auto_20190306_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damassetbatch',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
