# Generated by Django 2.1.7 on 2019-04-24 08:31

from django.db import (
    models,
    migrations,
)


class Migration(migrations.Migration):

    dependencies = [
        ('elsedam', '0029_add_batch_to_existed_dam_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='damasset',
            name='relative_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
